name: Deploy Angular Static Web App to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_LOCATION: "/"
  OUTPUT_LOCATION: "/dist/now-around-fe/browser"
  API_END_POINT: ${{ secrets.API_END_POINT }}
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
